name: Build TP Permission Unlock

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle 7.6
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.6'

      - name: Build
        working-directory: tp-permission-unlock
        run: gradle build --no-daemon --no-parallel --max-workers=2 --stacktrace
        env:
          GRADLE_OPTS: -Xmx2g -XX:MaxMetaspaceSize=512m

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: tp-permission-unlock-jar
          path: tp-permission-unlock/build/libs/*.jar
          if-no-files-found: error


